# @package _global_
solver:
  name: "grcwa"
  type: "rcwa"

  params:
    fourier_order: [49, 49]
    dtype: "complex128"
    n_lens_slices: 30
    grid_multiplier: 3

  convergence:
    auto_converge: false
    order_range: [5, 25]
    qe_tolerance: 0.01
